services:
  php:
    container_name: aurora-php
    image: secultceara/aurora:homolog
    restart: unless-stopped
    tty: true
    volumes:
      - uploads:/var/www/assets/uploads
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - postgres
      - mongo
    networks:
      - aurora_network

  nginx:
    container_name: aurora-nginx
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
    volumes:
      - uploads:/var/www/assets/uploads
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - aurora_network

  postgres:
    container_name: aurora-postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    tty: true
    volumes:
      - aurora-db:/var/lib/postgresql/data:rw
    networks:
      - aurora_network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-aurora_psql}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-aurora}

  mongo:
    container_name: aurora-mongo
    image: mongo:7.0
    tty: true
    restart: unless-stopped
    networks:
      - aurora_network
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-aurora_nosql}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGODB_DB: ${MONGODB_DB:-aurora_nosql}
      MONGODB_USER: ${MONGODB_USER:-aurora}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-password}
    volumes:
      - ./config/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

networks:
  aurora_network:
    driver: bridge

volumes:
  aurora-db:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/aurora-db
      o: bind
  uploads:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/uploads
      o: bind
